### SignUp
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{ 
  "username": "hillali3",
  "password": "1234",
  "role": 0,
  "withCreation": true
}

### Login a user
POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
  "email":"hillali3@gmail.com",
  "password": "1234"
}

### Chat Routes

### Get all chat IDs
GET http://localhost:3000/api/chats/6782eae383bc2bf38ce78a50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzAyMzQsImV4cCI6MTczNjYzMzgzNH0.jX98sOueS7j9GhkXo9J7BPaFEa3SBefGpxkxnjJ_rFw

### Get all posts
GET http://localhost:3000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzAyMzQsImV4cCI6MTczNjYzMzgzNH0.jX98sOueS7j9GhkXo9J7BPaFEa3SBefGpxkxnjJ_rFw

### Get chats by user ID
GET http://localhost:3000/api/chats/user/6782def65a30b06310406d42
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzAyMzQsImV4cCI6MTczNjYzMzgzNH0.jX98sOueS7j9GhkXo9J7BPaFEa3SBefGpxkxnjJ_rFw

### Get messages by chat ID
GET http://localhost:3000/api/chats/6782def65a30b06310406d42/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzAyMzQsImV4cCI6MTczNjYzMzgzNH0.jX98sOueS7j9GhkXo9J7BPaFEa3SBefGpxkxnjJ_rFw

### Skill Routes

### Get All skills
GET http://localhost:3000/api/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzQ0OTMsImV4cCI6MTczNjYzODA5M30.l6c11EaIpPLEHjgNIcAVukn928GIJw3mdX2tC7vmA6c

### Get skill by ID
GET http://localhost:3000/api/skills/6782ea1ca4039393f74f2490
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzI3ODAsImV4cCI6MTczNjYzNjM4MH0.Pfb-djxbfnv83hbVRird7tf8SM3WPaGo4JMbyROs-9A

### Create a new skill
POST http://localhost:3000/api/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg5MDU3ZGRkOWZmNTlmM2UyNTgyOTciLCJpYXQiOjE3MzcwMzMwOTAsImV4cCI6MTczNzAzNjY5MH0.FxlTN4w7wht-UvcKQh5WeVR2LHJELFKE6o2DXmZsvGg
Content-Type: application/json

{
  "name": "react"
}

### Update a skill by ID
PUT http://localhost:3000/api/skills/6782e9e9a4039393f74f2489
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzAyMzQsImV4cCI6MTczNjYzMzgzNH0.jX98sOueS7j9GhkXo9J7BPaFEa3SBefGpxkxnjJ_rFw
Content-Type: application/json

{
  "name": "TypeScript"
}

### Delete a skill by ID
DELETE http://localhost:3000/api/skills/6782e9e9a4039393f74f2489
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzgyZGVmNjVhMzBiMDYzMTA0MDZkNDIiLCJpYXQiOjE3MzY2MzAyMzQsImV4cCI6MTczNjYzMzgzNH0.jX98sOueS7j9GhkXo9J7BPaFEa3SBefGpxkxnjJ_rFw

### Create a new org
POST http://localhost:3000/api/organizations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2YjEwMjgwNjE0MWVhZmE3YjRjYTUiLCJpYXQiOjE3MzY4ODAzOTEsImV4cCI6MTczNjg4Mzk5MX0.x9HNnhllSOrjYctvGhZLONV8xTm7hX0zzGc3YAL8iIY
Content-Type: application/json

{
  "city": "83c4b530-e554-47a6-8cf3-94ea59c13703",
  "description": "regregteg",
  "email": "geva@gmail1.com",
  "focusAreas":[],
  "name": "fvfgeg",
  "password": "1234",
  "userId": "6785720c572547af6659705a",
  "websiteLink": "http://localhost:5173/signup/organization"
}

### Create a new volunteer
POST http://localhost:3000/api/volunteers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Nzg2YjEwMjgwNjE0MWVhZmE3YjRjYTUiLCJpYXQiOjE3MzY4ODAzOTEsImV4cCI6MTczNjg4Mzk5MX0.x9HNnhllSOrjYctvGhZLONV8xTm7hX0zzGc3YAL8iIY
Content-Type: application/json

{
  "userId": "6782def65a30b06310406d42",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com"
}